
CREATE TYPE funcao_usuario AS ENUM ('ADMIN', 'OPERADOR');
CREATE TYPE tipo_produto AS ENUM ('ACAI', 'SORVETE', 'SANDUICHE', 'SUCO', 'WHEY', 'BEBIDA', 'OUTRO');
CREATE TYPE forma_de_pagamento AS ENUM ('PIX', 'CREDITO', 'DEBITO', 'DINHEIRO');

CREATE TABLE usuarios (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_usuario VARCHAR(100) NOT NULL UNIQUE,
    senha_hash VARCHAR(60) NOT NULL,
    funcao funcao_usuario NOT NULL
);

CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL,
    tipo tipo_produto NOT NULL,
    variacao VARCHAR(60) NOT NULL,
    tamanho VARCHAR(20),
    preco DECIMAL(10,2) NOT NULL
);

CREATE TABLE complementos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(40) NOT NULL UNIQUE,
    preco_adicional DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE coberturas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(40) NOT NULL UNIQUE,
    preco_adicional DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda TIMESTAMP NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL,
    forma_pagamento forma_de_pagamento NOT NULL
);

CREATE TABLE venda_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INT NOT NULL,
    preco_unitario_da_venda DECIMAL(10,2) NOT NULL,
    CONSTRAINT fk_venda_itens_vendas FOREIGN KEY (venda_id) REFERENCES vendas (id) ON DELETE CASCADE,
    CONSTRAINT fk_venda_itens_produtos FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE TABLE venda_item_complementos (
    venda_item_id BIGINT NOT NULL,
    complemento_id BIGINT NOT NULL,
    quantidade INT NOT NULL DEFAULT 1,
    PRIMARY KEY (venda_item_id, complemento_id),
    CONSTRAINT fk_vic_venda_itens FOREIGN KEY (venda_item_id) REFERENCES venda_itens (id) ON DELETE CASCADE,
    CONSTRAINT fk_vic_complementos FOREIGN KEY (complemento_id) REFERENCES complementos (id)
);

CREATE TABLE venda_item_coberturas (
    venda_item_id BIGINT NOT NULL,
    cobertura_id BIGINT NOT NULL,
    quantidade INT NOT NULL DEFAULT 1,
    PRIMARY KEY (venda_item_id, cobertura_id),
    CONSTRAINT fk_vicob_venda_itens FOREIGN KEY (venda_item_id) REFERENCES venda_itens (id) ON DELETE CASCADE,
    CONSTRAINT fk_vicob_coberturas FOREIGN KEY (cobertura_id) REFERENCES coberturas (id)
);